# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-03 00:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, choices=[('HUC10', 'HUC10'), ('HUC12', 'HUC12'), ('RMU', 'RMU'), ('Pour Point', 'Pour Point')], default=None, max_length=20, null=True)),
                ('unit_id', models.IntegerField(blank=True, default=None, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Focus Area Geometry')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scenario_type', models.CharField(choices=[('Stream', 'Stream'), ('Forest', 'Forest'), ('Draw', 'Draw')], max_length=10)),
                ('focus_area', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ucsrb.FocusArea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('satisfied', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('planning_units', models.TextField(blank=True, null=True, verbose_name='Planning Unit IDs')),
                ('geometry_final_area', models.FloatField(blank=True, null=True, verbose_name='Total Area')),
                ('geometry_dissolved', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Scenario result dissolved')),
                ('private_own', models.BooleanField(default=False)),
                ('pub_priv_own', models.BooleanField(default=False)),
                ('pub_priv_own_input', models.CharField(blank=True, choices=[('Bureau of Land Management', 'Bureau of Land Management'), ('Bureau of Reclamation', 'Bureau of Reclamation'), ('National Park Service', 'National Park Service'), ('Native American Land', 'Native American Land'), ('Private land', 'Private Land'), ('Public Land', 'Public Land'), ('U.S. Air Force', 'U.S. Air Force'), ('U.S. Army', 'U.S. Army'), ('U.S. Fish & Wildlife Service', 'U.S. Fish & Wildlife Service'), ('USDA Forest Service', 'USDA Forest Service'), ('Washington Department of Fish & Wildlife', 'Washington Department of Fish & Wildlife'), ('Washington Department of Forestry', 'Washington Department of Forestry'), ('Washington Department of Natural Resources', 'Washington Department of Natural Resources'), ('Washington Department of Parks and Recreation', 'Washington Department of Parks and Recreation'), ('Washington State Government', 'Washington State Government')], default=None, max_length=255, null=True)),
                ('lsr_percent', models.BooleanField(default=False)),
                ('has_critical_habitat', models.BooleanField(default=False)),
                ('percent_roadless', models.BooleanField(default=False)),
                ('road_distance', models.BooleanField(default=False)),
                ('road_distance_max', models.FloatField(blank=True, default=None, null=True)),
                ('percent_wetland', models.BooleanField(default=False)),
                ('percent_riparian', models.BooleanField(default=False)),
                ('slope', models.BooleanField(default=False)),
                ('slope_max', models.FloatField(blank=True, default=None, null=True)),
                ('percent_fractional_coverage', models.BooleanField(default=False)),
                ('percent_fractional_coverage_min', models.FloatField(blank=True, default=None, null=True)),
                ('percent_fractional_coverage_max', models.FloatField(blank=True, default=None, null=True)),
                ('percent_high_fire_risk_area', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ucsrb_treatmentscenario_related', to='contenttypes.ContentType')),
                ('scenario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ucsrb.ScenarioState')),
                ('sharing_groups', models.ManyToManyField(blank=True, editable=False, related_name='ucsrb_treatmentscenario_related', to='auth.Group', verbose_name='Share with the following groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucsrb_treatmentscenario_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VegPlanningUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_unit_id', models.IntegerField()),
                ('veg_unit_id', models.IntegerField()),
                ('gridcode', models.IntegerField()),
                ('acres', models.FloatField()),
                ('huc_2_id', models.CharField(max_length=2)),
                ('huc_4_id', models.CharField(max_length=4)),
                ('huc_6_id', models.CharField(max_length=6)),
                ('huc_8_id', models.CharField(max_length=8)),
                ('huc_10_id', models.CharField(max_length=10)),
                ('huc_12_id', models.CharField(max_length=12)),
                ('pub_priv_own', models.CharField(max_length=255)),
                ('lsr_percent', models.FloatField()),
                ('has_critical_habitat', models.BooleanField(default=False)),
                ('percent_critical_habitat', models.FloatField()),
                ('percent_roadless', models.FloatField()),
                ('percent_wetland', models.FloatField()),
                ('percent_riparian', models.FloatField()),
                ('slope', models.FloatField()),
                ('road_distance', models.FloatField()),
                ('percent_fractional_coverage', models.FloatField()),
                ('percent_high_fire_risk_area', models.FloatField()),
                ('vegetation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('forest_height', models.IntegerField()),
                ('forest_class', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Veg Unit Geometry')),
            ],
        ),
    ]
