# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_auto_20171207_1705'),
        ('ucsrb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentScenario',
            fields=[
                ('scenario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scenarios.Scenario')),
            ],
            options={
                'abstract': False,
            },
            # bases=('scenarios.scenario',),
        ),
    ]
