# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariostate',
            name='focus_area',
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='focus_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='focus_area_input',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ucsrb.FocusArea'),
        ),
    ]
