# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0002_auto_20180205_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusarea',
            name='unit_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('HUC10', 'HUC10'), ('HUC12', 'HUC12'), ('RMU', 'RMU'), ('PourPoint', 'PourPoint'), ('Drawing', 'Drawing')], default=None, max_length=20, null=True),
        ),
    ]
