# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0002_treatmentscenario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegplanningunit',
            name='canopy_coverage',
        ),
        migrations.RemoveField(
            model_name='vegplanningunit',
            name='has_endangered_habitat',
        ),
        migrations.RemoveField(
            model_name='vegplanningunit',
            name='has_high_fire_risk',
        ),
        migrations.RemoveField(
            model_name='vegplanningunit',
            name='has_roads',
        ),
        migrations.RemoveField(
            model_name='vegplanningunit',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='vegplanningunit',
            name='miles_from_road_access',
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='acres',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='gridcode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='huc_10_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='huc_12_id',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='huc_2_id',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='huc_4_id',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='huc_6_id',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='huc_8_id',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='lsr_percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='percent_critical_habitat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='percent_fractional_coverage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='percent_high_fire_risk_area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='percent_riparian',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='percent_roadless',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='percent_wetland',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='planning_unit_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='pub_priv_own',
            field=models.CharField(default='public', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='road_distance',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='veg_unit_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vegplanningunit',
            name='slope',
            field=models.FloatField(),
        ),
    ]
