# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0003_auto_20171214_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegplanningunit',
            name='has_critical_habitat',
            field=models.BooleanField(default=False),
        ),
    ]
