# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0003_auto_20180207_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusarea',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
