# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0004_focusarea_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PourPointBasin',
            fields=[
                ('ppt_ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Pour Point ID')),
                ('area', models.FloatField(blank=True, default=None, null=True, verbose_name='Area in Acres')),
                ('mean_elev', models.IntegerField(blank=True, default=None, null=True, verbose_name='Mean Elevation')),
                ('avg_slp', models.FloatField(blank=True, default=None, null=True, verbose_name='Average Slope')),
                ('slp_gt60', models.IntegerField(default=0, verbose_name='Percent Area w/ Slope > 60%')),
                ('elev_dif', models.IntegerField(blank=True, default=None, null=True, verbose_name='Elevation Difference in Meters')),
                ('mean_shade', models.IntegerField(blank=True, default=None, null=True, verbose_name='Mean Shaded Area')),
                ('veg_prop', models.IntegerField(blank=True, default=None, null=True, verbose_name='Percent Forested')),
                ('thc_11', models.IntegerField(verbose_name='Topo-Height Class 11')),
                ('thc_12', models.IntegerField(verbose_name='Topo-Height Class 12')),
                ('thc_13', models.IntegerField(verbose_name='Topo-Height Class 13')),
                ('thc_14', models.IntegerField(verbose_name='Topo-Height Class 14')),
                ('thc_15', models.IntegerField(verbose_name='Topo-Height Class 15')),
                ('thc_21', models.IntegerField(verbose_name='Topo-Height Class 21')),
                ('thc_22', models.IntegerField(verbose_name='Topo-Height Class 22')),
                ('thc_23', models.IntegerField(verbose_name='Topo-Height Class 23')),
                ('thc_24', models.IntegerField(verbose_name='Topo-Height Class 24')),
                ('thc_25', models.IntegerField(verbose_name='Topo-Height Class 25')),
                ('fc_11', models.IntegerField(verbose_name='Fractional Coverage 11')),
                ('fc_12', models.IntegerField(verbose_name='Fractional Coverage 12')),
                ('fc_13', models.IntegerField(verbose_name='Fractional Coverage 13')),
                ('fc_14', models.IntegerField(verbose_name='Fractional Coverage 14')),
                ('fc_15', models.IntegerField(verbose_name='Fractional Coverage 15')),
                ('fc_21', models.IntegerField(verbose_name='Fractional Coverage 21')),
                ('fc_22', models.IntegerField(verbose_name='Fractional Coverage 22')),
                ('fc_23', models.IntegerField(verbose_name='Fractional Coverage 23')),
                ('fc_24', models.IntegerField(verbose_name='Fractional Coverage 24')),
                ('fc_25', models.IntegerField(verbose_name='Fractional Coverage 25')),
                ('dwnst_ppt', models.IntegerField(blank=True, default=None, null=True, verbose_name='Downstream Pourpoint ID')),
            ],
        ),
    ]
