# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 01:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ucsrb', '0004_vegplanningunit_has_critical_habitat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, choices=[('HUC10', 'HUC10'), ('HUC12', 'HUC12'), ('RMU', 'RMU'), ('Pour Point', 'Pour Point')], default=None, max_length=20, null=True)),
                ('unit_id', models.IntegerField(blank=True, default=None, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Focus Area Geometry')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scenario_type', models.CharField(choices=[('Stream', 'Stream'), ('Forest', 'Forest'), ('Draw', 'Draw')], max_length=10)),
                ('focus_area', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ucsrb.FocusArea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_max_percent_fractional_coverage',
            field=models.FloatField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_max_road_distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_max_slope',
            field=models.FloatField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_min_percent_fractional_coverage',
            field=models.FloatField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_parameter_has_critical_habitat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_parameter_lsr_percent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_parameter_percent_fractional_coverage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_parameter_percent_high_fire_risk_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_parameter_percent_riparian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_parameter_percent_roadless',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_parameter_percent_wetland',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_parameter_private_own',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_parameter_pub_priv_own',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_parameter_road_distance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_parameter_slope',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='input_pub_priv_own',
            field=models.CharField(blank=True, choices=[('Bureau of Land Management', 'Bureau of Land Management'), ('Bureau of Reclamation', 'Bureau of Reclamation'), ('National Park Service', 'National Park Service'), ('Native American Land', 'Native American Land'), ('Private land', 'Private Land'), ('Public Land', 'Public Land'), ('U.S. Air Force', 'U.S. Air Force'), ('U.S. Army', 'U.S. Army'), ('U.S. Fish & Wildlife Service', 'U.S. Fish & Wildlife Service'), ('USDA Forest Service', 'USDA Forest Service'), ('Washington Department of Fish & Wildlife', 'Washington Department of Fish & Wildlife'), ('Washington Department of Forestry', 'Washington Department of Forestry'), ('Washington Department of Natural Resources', 'Washington Department of Natural Resources'), ('Washington Department of Parks and Recreation', 'Washington Department of Parks and Recreation'), ('Washington State Government', 'Washington State Government')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='scenario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ucsrb.ScenarioState'),
        ),
    ]
