# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 02:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0005_auto_20180126_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegplanningunit',
            name='planningunit_ptr',
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='new_geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Veg Unit Geometry'),
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='new_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatmentscenario',
            name='input_max_percent_fractional_coverage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentscenario',
            name='input_max_slope',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentscenario',
            name='input_min_percent_fractional_coverage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentscenario',
            name='input_pub_priv_own',
            field=models.CharField(blank=True, choices=[('Bureau of Land Management', 'Bureau of Land Management'), ('Bureau of Reclamation', 'Bureau of Reclamation'), ('National Park Service', 'National Park Service'), ('Native American Land', 'Native American Land'), ('Private land', 'Private Land'), ('Public Land', 'Public Land'), ('U.S. Air Force', 'U.S. Air Force'), ('U.S. Army', 'U.S. Army'), ('U.S. Fish & Wildlife Service', 'U.S. Fish & Wildlife Service'), ('USDA Forest Service', 'USDA Forest Service'), ('Washington Department of Fish & Wildlife', 'Washington Department of Fish & Wildlife'), ('Washington Department of Forestry', 'Washington Department of Forestry'), ('Washington Department of Natural Resources', 'Washington Department of Natural Resources'), ('Washington Department of Parks and Recreation', 'Washington Department of Parks and Recreation'), ('Washington State Government', 'Washington State Government')], default=None, max_length=255, null=True),
        ),
    ]
