# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0005_pourpointbasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_id', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('temp', models.IntegerField(verbose_name='temperature')),
                ('pcp', models.IntegerField(verbose_name='precipitation')),
                ('albedo', models.FloatField()),
                ('wind', models.IntegerField()),
                ('rh', models.FloatField(verbose_name='relative humidity')),
            ],
        ),
    ]
