# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 17:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0006_auto_20180130_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVegPlanningUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('planning_unit_id', models.IntegerField()),
                ('veg_unit_id', models.IntegerField()),
                ('gridcode', models.IntegerField()),
                ('acres', models.FloatField()),
                ('huc_2_id', models.CharField(max_length=2)),
                ('huc_4_id', models.CharField(max_length=4)),
                ('huc_6_id', models.CharField(max_length=6)),
                ('huc_8_id', models.CharField(max_length=8)),
                ('huc_10_id', models.CharField(max_length=10)),
                ('huc_12_id', models.CharField(max_length=12)),
                ('pub_priv_own', models.CharField(max_length=255)),
                ('lsr_percent', models.FloatField()),
                ('has_critical_habitat', models.BooleanField(default=False)),
                ('percent_critical_habitat', models.FloatField()),
                ('percent_roadless', models.FloatField()),
                ('percent_wetland', models.FloatField()),
                ('percent_riparian', models.FloatField()),
                ('slope', models.FloatField()),
                ('road_distance', models.FloatField()),
                ('percent_fractional_coverage', models.FloatField()),
                ('percent_high_fire_risk_area', models.FloatField()),
                ('vegetation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('forest_height', models.IntegerField()),
                ('forest_class', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Veg Unit Geometry')),
            ],
        ),
        migrations.DeleteModel(
            name='VegPlanningUnit',
        ),
    ]
