# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0006_climatedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='pcp',
            field=models.FloatField(verbose_name='precipitation'),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='wind',
            field=models.FloatField(),
        ),
    ]
