# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0007_auto_20180131_0959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewVegPlanningUnit',
            new_name='VegPlanningUnit',
        ),
    ]
