# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 16:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0007_auto_20180323_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='PourPoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Pour Point ID')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857, verbose_name='Pour Point')),
            ],
        ),
    ]
