# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-27 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0008_pourpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegplanningunit',
            name='forest_class',
        ),
        migrations.RemoveField(
            model_name='vegplanningunit',
            name='forest_height',
        ),
        migrations.RemoveField(
            model_name='vegplanningunit',
            name='vegetation_type',
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('HUC10', 'HUC10'), ('HUC12', 'HUC12'), ('RMA', 'RMA'), ('PourPointOverlap', 'PourPointOverlap'), ('PourPointDiscrete', 'PourPointDiscrete'), ('Drawing', 'Drawing')], default=None, max_length=20, null=True),
        ),
    ]
