# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0009_auto_20180627_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegplanningunit',
            name='dwnstream_ppt_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='mgmt_alloc_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='mgmt_description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='mgmt_unit_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='topo_height_class_majority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
