# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 22:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ucsrb', '0009_auto_20180131_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentscenario',
            name='scenario_ptr',
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ucsrb_treatmentscenario_related', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='geometry_dissolved',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Scenario result dissolved'),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='geometry_final_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Area'),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='name',
            field=models.CharField(default='treatment', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='planning_units',
            field=models.TextField(blank=True, null=True, verbose_name='Planning Unit IDs'),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='satisfied',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='ucsrb_treatmentscenario_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ucsrb_treatmentscenario_related', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
