# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0010_auto_20180131_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentscenario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
