# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-05 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0010_auto_20180628_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='pourpointbasin',
            name='SDsphrical',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='bbl_prsr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='bulk_dens',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='cap_drv',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='center_x',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='center_y',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='exp_decrs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='field_cap',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='lat_con',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='mannings',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='max_inf',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='normal_x',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='normal_y',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='normal_z',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='pore_sz',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='porosity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='vert_con',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pourpointbasin',
            name='wilt_pt',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
