# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 12:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0011_auto_20180705_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusarea',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('HUC10', 'HUC10'), ('HUC12', 'HUC12'), ('RMU', 'RMU'), ('PourPointOverlap', 'PourPointOverlap'), ('PourPointDiscrete', 'PourPointDiscrete'), ('Drawing', 'Drawing')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vegplanningunit',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857, verbose_name='Veg Unit Geometry'),
        ),
    ]
