# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0011_auto_20180131_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_parameter_has_critical_habitat',
            new_name='has_critical_habitat',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_parameter_lsr_percent',
            new_name='lsr_percent',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_parameter_percent_fractional_coverage',
            new_name='percent_fractional_coverage',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_max_percent_fractional_coverage',
            new_name='percent_fractional_coverage_max',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_min_percent_fractional_coverage',
            new_name='percent_fractional_coverage_min',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_parameter_percent_high_fire_risk_area',
            new_name='percent_high_fire_risk_area',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_parameter_percent_riparian',
            new_name='percent_riparian',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_parameter_percent_roadless',
            new_name='percent_roadless',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_parameter_percent_wetland',
            new_name='percent_wetland',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_parameter_private_own',
            new_name='private_own',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_parameter_pub_priv_own',
            new_name='pub_priv_own',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_pub_priv_own',
            new_name='pub_priv_own_input',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_parameter_road_distance',
            new_name='road_distance',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_max_road_distance',
            new_name='road_distance_max',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_parameter_slope',
            new_name='slope',
        ),
        migrations.RenameField(
            model_name='treatmentscenario',
            old_name='input_max_slope',
            new_name='slope_max',
        ),
    ]
