# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0012_auto_20180710_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentscenario',
            name='landform_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='landform_type_checkboxes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='landform_type_checkboxes_include_east_west',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='landform_type_checkboxes_include_floor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='landform_type_checkboxes_include_north',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='landform_type_checkboxes_include_ridgetop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='landform_type_checkboxes_include_south',
            field=models.BooleanField(default=True),
        ),
    ]
