# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-31 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0013_auto_20180710_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentscenario',
            name='aggregate_report',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
