# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0015_auto_20180805_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='pourpoint',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
    ]
