# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-29 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0016_pourpoint_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentscenario',
            name='has_burned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='has_wilderness_area',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='has_burned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vegplanningunit',
            name='has_wilderness_area',
            field=models.BooleanField(default=False),
        ),
    ]
