# Generated by Django 2.2.19 on 2021-03-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0017_auto_20181129_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentscenario',
            name='prescription_treatment_selection',
            field=models.CharField(blank=True, choices=[('notr', 'No Treatment scenario'), ('mb16', 'Maximum Biomass 16 inch scenario'), ('mb25', 'Maximum Biomass 25 inch scenario'), ('burn', 'Burn Only scenario'), ('flow', 'Ideal Water scenario')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pourpoint',
            name='imputed_ppt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ucsrb.PourPoint', verbose_name='Nearest Neighbor Match'),
        ),
        migrations.AlterField(
            model_name='treatmentscenario',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ucsrb_treatmentscenario_related', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='treatmentscenario',
            name='focus_area_input',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ucsrb.FocusArea'),
        ),
        migrations.AlterField(
            model_name='treatmentscenario',
            name='geometry_final_area',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Total Area'),
        ),
        migrations.AlterField(
            model_name='treatmentscenario',
            name='planning_units',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Planning Unit IDs'),
        ),
    ]
