# Generated by Django 2.2.17 on 2021-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0019_streamflowreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamflowreading',
            name='is_baseline',
            field=models.BooleanField(default=False, verbose_name='This is a baseline reading'),
        ),
    ]
