# Generated by Django 2.2.17 on 2021-03-08 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0022_auto_20210308_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamflowreading',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reading DateTime'),
            preserve_default=False,
        ),
    ]
