# Generated by Django 2.2.19 on 2021-03-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0023_streamflowreading_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimateData',
        ),
        migrations.DeleteModel(
            name='ScenarioNNLookup',
        ),
        migrations.AlterField(
            model_name='pourpoint',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Pour Point ID'),
        ),
        migrations.AlterField(
            model_name='pourpointbasin',
            name='ppt_ID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Pour Point ID'),
        ),
        migrations.AlterField(
            model_name='vegplanningunit',
            name='dwnstream_ppt_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
