# Generated by Django 2.2.19 on 2021-03-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0024_auto_20210312_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamflowreading',
            name='basin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucsrb.FocusArea', verbose_name='Stream Segment Basin'),
        ),
        migrations.DeleteModel(
            name='PourPointBasin',
        ),
    ]
