# Generated by Django 2.2.19 on 2021-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0025_auto_20210317_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamflowreading',
            name='segment_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Streat Segment ID'),
        ),
    ]
