# Generated by Django 2.2.19 on 2021-03-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0026_streamflowreading_segment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamflowreading',
            name='basin',
        ),
    ]
