# Generated by Django 2.2.19 on 2021-09-07 14:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0027_remove_streamflowreading_basin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_treatment_selection', models.CharField(blank=True, choices=[('notr', 'No Treatment scenario'), ('mb16', 'Maximum Biomass 16 inch scenario'), ('mb25', 'Maximum Biomass 25 inch scenario'), ('burn', 'Burn Only scenario'), ('flow', 'Ideal Water scenario')], default=None, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857, verbose_name='Treatment Area Geometry')),
                ('scenario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ucsrb.TreatmentScenario')),
            ],
        ),
    ]
