# Generated by Django 2.2.19 on 2021-04-28 11:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0027_remove_streamflowreading_basin'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentscenario',
            name='rx_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentscenario',
            name='scenario_geometry',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=3857, verbose_name='User Defined Geometries'),
        ),
    ]
