# Generated by Django 2.2.19 on 2021-07-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0028_auto_20210428_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentscenario',
            name='prescription_treatment_selection',
            field=models.CharField(blank=True, choices=[('notr', 'No Treatment scenario'), ('mb16', 'Maximum Biomass 16 inch scenario'), ('mb25', 'Maximum Biomass 25 inch scenario'), ('burn', 'Burn Only scenario'), ('flow', 'Ideal Water scenario')], default='notr', max_length=255, null=True),
        ),
    ]
