# Generated by Django 2.2.19 on 2021-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0028_treatmentarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentarea',
            name='prescription_treatment_selection',
            field=models.CharField(blank=True, choices=[('notr', 'No Treatment'), ('mb16', 'Maximum Biomass 16 Inch Limit'), ('mb25', 'Maximum Biomass 25 Inch Limit'), ('burn', 'Burn Only'), ('flow', 'Ideal Water')], default='notr', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentscenario',
            name='prescription_treatment_selection',
            field=models.CharField(blank=True, choices=[('notr', 'No Treatment'), ('mb16', 'Maximum Biomass 16 Inch Limit'), ('mb25', 'Maximum Biomass 25 Inch Limit'), ('burn', 'Burn Only'), ('flow', 'Ideal Water')], default=None, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='streamflowreading',
            index=models.Index(fields=['segment_id'], name='ucsrb_strea_segment_f8c28c_idx'),
        ),
        migrations.AddIndex(
            model_name='streamflowreading',
            index=models.Index(fields=['treatment'], name='ucsrb_strea_treatme_02d6da_idx'),
        ),
        migrations.AddIndex(
            model_name='streamflowreading',
            index=models.Index(fields=['is_baseline'], name='ucsrb_strea_is_base_abb780_idx'),
        ),
    ]
