# Generated by Django 2.2.19 on 2021-10-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucsrb', '0029_auto_20211006_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_year', models.CharField(choices=[('dry', 'dry'), ('normal', 'normal'), ('wet', 'wet')], max_length=32)),
                ('task_id', models.CharField(max_length=255)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucsrb.TreatmentScenario')),
            ],
            options={
                'unique_together': {('scenario', 'weather_year')},
            },
        ),
    ]
